version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 20
      runas: root
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 20
      runas: root
